# Generated by Django 2.0.1 on 2020-04-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('short_name', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tech1',
            fields=[
                ('url', models.CharField(max_length=100)),
                ('config', models.CharField(max_length=200)),
                ('config_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
