# Generated by Django 2.0.1 on 2020-04-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech',
            old_name='id',
            new_name='ConfigDifference',
        ),
        migrations.RenameField(
            model_name='tech',
            old_name='short_name',
            new_name='Device1IP',
        ),
        migrations.RenameField(
            model_name='tech',
            old_name='name',
            new_name='Device2IP',
        ),
        migrations.RenameField(
            model_name='tech1',
            old_name='config_id',
            new_name='Average',
        ),
        migrations.RenameField(
            model_name='tech1',
            old_name='config',
            new_name='BWUtilization',
        ),
        migrations.RenameField(
            model_name='tech1',
            old_name='url',
            new_name='DeviceIP',
        ),
    ]
