# Generated by Django 2.0.1 on 2020-04-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200401_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tech',
            old_name='Device2IP',
            new_name='Account_Name',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='Device1IP',
        ),
        migrations.AddField(
            model_name='tech',
            name='DeviceIP',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='tech1',
            name='Account_Name',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
