# Generated by Django 2.0.1 on 2020-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20200401_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='ConfigDifference',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
