# Generated by Django 2.1.7 on 2020-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20200401_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='DeviceIP',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
