# Generated by Django 2.1.7 on 2020-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20200401_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='DeviceIP',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
