# Generated by Django 2.1.7 on 2020-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20200401_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='DeviceIP',
            field=models.CharField(max_length=100),
        ),
    ]
