# Generated by Django 2.1.7 on 2020-04-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20200401_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech1',
            name='Account_Name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
