# Generated by Django 2.1.7 on 2020-04-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20200401_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='DeviceIP',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='tech1',
            name='Account_Name',
            field=models.CharField(default='', editable=False, max_length=200),
        ),
    ]
